language: python
sudo: true
matrix:
  include:
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
  fast_finish: true
install:
  - apt-cache depends python-pycurl 
  - sudo apt-get install libcurl4-gnutls-dev libgnutls-dev
  - sudo apt-get install -y gnutls-bin 
  - pip install Django wheel "pycurl==7.43.0" "certifi==2017.7.27.1" PyVimeo -U pip
script:
  - python manage.py test
