language: python
sudo: false
matrix:
  include:
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
  fast_finish: true
install:
  - install-gnutls.sh 
  - pip install "requests>=2.4.0" "tuspy==0.2.1" "certifi==2017.7.27.1" "PycURL==7.43.0" Django PyVimeo -U pip
