language: python
sudo: false
matrix:
  include:
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
  fast_finish: true
install:
  - pip install PycURL Django PyVimeo -U pip
